# Generated by Django 2.0.5 on 2018-05-28 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorateStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(upload_to='')),
                ('eng_name', models.CharField(max_length=100)),
                ('zh_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('research_interests', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MasterStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(upload_to='')),
                ('eng_name', models.CharField(max_length=100)),
                ('zh_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('research_interests', models.TextField()),
                ('year_of_study', models.CharField(choices=[('FIRST', 'First'), ('SECOND', 'Second'), ('THIRD', 'Third'), ('FOURTH', 'Fourth'), ('FIFTH', 'Fifth')], default='FIRST', max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
