# Generated by Django 2.0.5 on 2018-05-28 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoratestudent',
            name='eng_name',
            field=models.CharField(max_length=100, verbose_name='English name'),
        ),
        migrations.AlterField(
            model_name='doctoratestudent',
            name='zh_name',
            field=models.CharField(max_length=100, verbose_name='Chinese name'),
        ),
        migrations.AlterField(
            model_name='masterstudent',
            name='eng_name',
            field=models.CharField(max_length=100, verbose_name='English name'),
        ),
        migrations.AlterField(
            model_name='masterstudent',
            name='year_of_study',
            field=models.CharField(choices=[('FIRST', 'First'), ('SECOND', 'Second'), ('THIRD', 'Third'), ('FOURTH', 'Fourth'), ('FIFTH', 'Fifth')], default='FIRST', max_length=10),
        ),
        migrations.AlterField(
            model_name='masterstudent',
            name='zh_name',
            field=models.CharField(max_length=100, verbose_name='Chinese name'),
        ),
    ]
