# Generated by Django 2.0.5 on 2018-05-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20180528_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoratestudent',
            name='profile_picture',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='masterstudent',
            name='profile_picture',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
