# Generated by Django 2.0.6 on 2018-06-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_faculty_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterstudent',
            name='year_of_study',
            field=models.CharField(choices=[('FIRST', 'First'), ('SECOND', 'Second'), ('THIRD', 'Third'), ('FOURTH', 'Fourth'), ('GRAD', 'Graduated')], default='FIRST', max_length=10),
        ),
    ]
