version: '3'

services:
  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  nginx:
    image: nginx
    container_name: gil_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - .:/code
      - ./config/nginx:/etc/nginx/conf.d
      - ./staticfiles:/code/staticfiles
      - ./media:/code/gil_website/media
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - web
  db:
    image: postgres
    container_name: gil_postgres
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf

  web:
    build: .
    container_name: gil_django
    restart: always
    env_file:
      - web-variables.env
    command: >
      bash -c "python manage.py makemigrations --noinput
      && python manage.py migrate --noinput
      && python manage.py collectstatic --noinput
      && gunicorn gil_configuration.wsgi:application -b :80 --workers 4"
    volumes:
#      - .:/code
      - ./staticfiles:/code/staticfiles
      - ./media:/code/gil_website/media
    depends_on:
      - db
  cache:
    image: memcached
    restart: always
    container_name: gil_memcached
    entrypoint:
      - memcached
      - -m 64

