# Generated by Django 2.0.7 on 2018-07-06 05:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('time_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('file', models.FileField(blank=True, upload_to='uploads/news')),
                ('type_of_event', models.CharField(choices=[('NEWS', 'News'), ('TALKS_EVENTS', 'Talks/Events')], default='NEWS', max_length=200)),
            ],
        ),
    ]
